service: recommendation

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 10
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  getRecommendation:
    image:
      name: appimage
      events:
        - httpApi:
            method: POST
            path: /api/v1/recommendation
            cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
