service: recommendation

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 5
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  getRecommendation:
    handler: src/recommendation.handler
    memorySize: 2048
    events:
      - http:
          method: post
          path: /api/v1/recommendation
          cors: true

plugins:
  - serverless-offline
