service: recommendations

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 10
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

custom:
  pythonRequirements:
    zip: true
    slim: true

functions:
  getRecommendation:
    events:
      - http:
          method: POST
          path: /api/v1/recommendation
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
