service: food

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 10
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
          Resource: "arn:aws:s3:::tiociufood/*"

functions:
  addFood:
    handler: src/add.handler
    memorySize: 512
    events:
      - http:
          path: /api/v1/food/add
          method: post
          cors: true
  getFood:
    handler: src/get.handler
    events:
      - http:
          path: /api/v1/food
          method: get
          cors: true
  getFoodDetail:
    handler: src/detail.handler
    events:
      - http:
          path: /api/v1/food
          method: post
          cors: true

plugins:
  - serverless-offline
