service: restaurant

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 3

functions:
  getRestaurant:
    handler: src/restaurant.addRestaurant
    events:
      - http:
          path: /api/v1/restaurant/add
          method: post
          cors: true