service: restaurant

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 3
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
          Resource: "arn:aws:s3:::tiociufood/*"

functions:
  addRestaurant:
    handler: src/restaurant.addRestaurant
    events:
      - http:
          path: /api/v1/restaurant/add
          method: post
          cors: true
  getRestaurant:
    handler: src/restaurant.getRestaurant
    events:
      - http:
          path: /api/v1/restaurant
          method: get
          cors: true