service: review

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 5
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:Update
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  reviewRestaurant:
    handler: src/reviewRestaurant.handler
    memorySize: 128
    events:
      - http:
          path: /api/v1/review/restaurant/add
          method: post
          cors: true
  reviewFood:
    handler: src/reviewFood.handler
    memorySize: 128
    events:
      - http:
          path: /api/v1/review/food/add
          method: post
          cors: true

plugins:
  - serverless-offline
