service: training

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 5
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  getTrainingData:
    handler: src/getTrainingData.handler
    memorySize: 128
    events:
      - http:
          path: /api/v1/training
          method: get
          cors: true
  getCosineSimilarity:
    handler: src/getCosineSimilarity.handler
    memorySize: 128
    events:
      - http:
          path: /api/v1/training/similarity
          method: post
          cors: true
  getTrainingRecommendation:
    handler: src/getTrainingRecommendation.handler
    memorySize: 512
    events:
      - http:
          path: /api/v1/training/recommendation
          method: post
          cors: true

plugins:
  - serverless-offline
