service: auth

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  timeout: 3
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

package:
  individually: true

functions:
  addAdmin:
    handler: src/admin.add
    events:
      - http:
          path: /api/v1/auth/admin/add
          method: post
          cors: true
  loginAdmin:
    handler: src/admin.login
    events:
      - http:
          path: /api/v1/auth/admin/login
          method: post
          cors: true
  addUser:
    handler: src/user.add
    events:
      - http:
          path: /api/v1/auth/user/add
          method: post
          cors: true
  loginUser:
    handler: src/user.login
    events:
      - http:
          path: /api/v1/auth/user/login
          method: post
          cors: true
  getUser:
    handler: src/user.get
    events:
      - http:
          path: /api/v1/auth/user
          method: get
          cors: true

plugins:
  - serverless-offline
