service: auth

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt::stage, 'dev'}
  timeout: 3

functions:
  addAdmin:
    handler: src/admin.add
    events:
      - http:
          path: /api/v1/admin/add
          method: get
          cors: true
